### ISSUE TITLE
Create User model [Tracking Issue]

### ISSUE THREAD

**Issue by ernest-phillips** [ernest-phillips/home_inventory#8]
### Objective

The objective of this GitHub issue is to build out the user model in a Rails project. The user model should include an email address, password, and name for each user.

### Steps to Complete

```[tasklist]
### Tasks
- [ ] Generate a user model by running the following command in the terminal: `rails generate model User email:string password:string name:string`.
- [ ] Run the migration for the user model by running the following command in the terminal: `rails db:migrate`.
- [ ] Add validations for each attribute in the user model. For example, the email attribute should be unique and have a valid format.
- [ ] https://github.com/ernest-phillips/home_inventory/issues/5
- [ ] https://github.com/ernest-phillips/home_inventory/issues/4
- [ ] https://github.com/ernest-phillips/home_inventory/issues/3
```

### Expected Outcome

The expected outcome of completing this GitHub issue is to have a fully functional user model that includes email, password, and name attributes. Users should be able to register for an account and login using their email and password.
